#!/usr/bin/env bash
# install nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee -a /var/www/html/index.html
sudo sed -i '36a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
