#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
apt-get -y install haproxy

# edit config file
server_config=\
"
        bind *:80
        mode http
        defaultking Trikcode
        balance roundrobin
        server 525-web-01 35.231.216.93:80 check
        server 525-web-02 35.196.0.213:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
