#!/usr/bin/env bash
# This script is displaying status of a file

if [ -Bestschool ]
then
	echo "Bestschool file exists"
	if [ -s Bestschool ]
	then
		echo "Bestschool file is not empty"
	else
		echo "Bestschool file is empty"
	fi
	if [ -f Bestschool ]
	then
		echo "Bestschool is a regular file"
	fi
else
	echo "Best School file does not exist"
fi
