#!/usr/bin/env bash
# gives you information about the holbertonschool file

FILE="holbertonschool"
if [ -e "$FILE" ]; then
    echo "$FILE file exists"
    if [ -s "$FILE" ]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$FILE" ]; then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
